---
- name: chromium | ubuntu facts
  set_fact:
    chromium_name: chromium-browser
    chromium_default: /etc/chromium-browser/customizations/01-hawken-browser
    chromium_policies: /etc/chromium-browser/policies
  when: ansible_distribution == 'Ubuntu'

- name: chromium | debian facts
  set_fact:
    chromium_name: chromium
    chromium_default: /etc/chromium.d/01-hawken-browser
    chromium_policies: /etc/chromium/policies
  when: ansible_distribution == 'Debian'

- name: chromium | install
  apt:
    name: "{{ chromium_name }}"

- name: chromium | set flags
  template:
    src: files/etc/chromium/hawken-browser
    dest: "{{ chromium_default }}"

- name: chromium | ensure policies dir
  file:
    path: "{{ chromium_policies }}/managed"
    state: directory

- name: chromium | set managed policies
  template:
    src: files/etc/chromium/policies/managed/hawken-browser.json
    dest: "{{ chromium_policies }}/managed/hawken-browser.json"
