---
- name: firefox | ubuntu facts
  set_fact:
    firefox_name: firefox
    config_loader: syspref.js
  when: ansible_distribution == 'Ubuntu'

- name: firefox | debian facts
  set_fact:
    firefox_name: firefox-esr
    config_loader: hawken-browser.js
  when: ansible_distribution == 'Debian'

- name: firefox | install
  apt:
    name: "{{ firefox_name }}"

- name: firefox | policies.json
  template:
    src: files/usr/lib/firefox/distribution/policies.json
    dest: "/usr/lib/{{ firefox_name }}/distribution/policies.json"

- name: firefox | general.config loader
  template:
    src: files/etc/firefox/hawken-browser.js
    dest: "/etc/{{ firefox_name }}/hawken-browser.js"

- name: firefox | config file
  template:
    src: files/usr/lib/firefox/hawken-browser.cfg
    dest: "/usr/lib/{{ firefox_name }}/hawken-browser.cfg"
